name: CI
env:
  SCREENER_API_KEY: ${{secrets.SCREENER_API_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

on:
  push:
    branches: [development]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          cd reactjs-2022
          npm ci
      - name: Build the app
        run: |
          cd reactjs-2022
          npm run build
      - name: Run component tests
        run: |
          cd reactjs-2022
          npm run tests
      - name: Start the app
        run: |
          cd reactjs-2022
          npm Start &
          npx wait-on --timeout 60000
